### ISSUE TITLE
QA issues with the repository

### ISSUE THREAD

**Issue by mgorny** [das-labor/overlay#10]
There's [Gentoo bug #613470](https://bugs.gentoo.org/show_bug.cgi?id=613470) open for QA issues with the repo. Please urgently fix those issues (you may need to refresh the report 30 minutes after push to see if it doesn't find more) or at least respond to the bug. Otherwise, the repository will be removed from the list.

**Comment by zaolin** [comment]
I didn't know that we have to do QA for gentoo overlays. I will fix the issues this weekend.

**Comment by flanfly** [comment]
Call me stupid, but what exactly is the issue here?
```
{'description': {'en': 'Gentoo overlay from Hackerspace Bochum'},
 'homepage': 'https://github.com/das-labor/labor-overlay',
 'name': 'das-labor',
 'owner': [{'email': 'zaolin@das-labor.org',
            'name': 'Philipp Deppenwiese',
            'type': 'person'},
           {'email': 'kai@gnupg.org',
            'name': 'Kai Michaelis',
            'type': 'person'}],
 'quality': 'experimental',
 'source': [{'type': 'git',
             'uri': 'https://github.com/das-labor/labor-overlay.git'}],
 'status': 'unofficial'}
$ pmaint sync das-labor
Already up-to-date.
*** syncing das-labor
*** synced das-labor
 * Sync succeeded
$ git log --format=%ci -1
$ pmaint regen --use-local-desc --pkg-desc-index -t 1 das-labor
 * Cache regenerated successfully
```

**Comment by mgorny** [comment]
I'm sorry, it wasn't closed as fixed automatically due to Kai's e-mail address mismatch. Now that's solved, there's nothing more to do.

**Comment by flanfly** [comment]
👍
