### ISSUE TITLE
veracrypt-1.17: digest verification failed

### ISSUE THREAD

**Issue by bitpick** [das-labor/overlay#2]
on emerge, the following error occured:
!!! Digest verification failed:
!!! /var/lib/layman/labor-overlay/app-crypt/veracrypt/files/execstack_fix.diff
!!! Reason: Filesize does not match recorded size
!!! Got: 2387
!!! Expected: 2463

but `ebuild veracrypt-1.17.ebuild merge` worked before committing files (incl. Manifest file), indicating correct hashes...

Any ideas on the reason?

**Comment by orangecms** [comment]
Closing this, as we don't have veracrypt in this overlay anymore. It's available in the main Gentoo ports tree.
