### ISSUE TITLE
Build failures for usbguard-0.7.2 ebuild.

### ISSUE THREAD

**Issue by noci2012** [das-labor/overlay#28]
The build flags were: 
\# emerge -av usbguard  
[ebuild  N    ] sys-apps/usbguard-0.7.2  USE="crypt crypt_gcrypt dbus policykit -crypt_sodium -qt4 -qt5 -systemd" 

Would you like to merge these packages? [Yes/No] y

(Systemd directories get filtered).

usbguard ebuild fails due to lack of RDEPEND on asciidoctor
after installing that: 
The install fails with:
libtool: install: /usr/lib/portage/python3.5/ebuild-helpers/xattr/install -c .libs/usbguard-daemon /var/tmp/portage/sys-apps/usbguard-0.7.2/image//usr/sbin/usbguard-daemon
libtool: warning: remember to run 'libtool --finish /usr/lib64'
 /bin/mkdir -p '/var/tmp/portage/sys-apps/usbguard-0.7.2/image//usr/bin'
  /bin/sh ./libtool   --mode=install /usr/lib/portage/python3.5/ebuild-helpers/xattr/install -c usbguard usbguard-rule-parser '/var/tmp/portage/sys-apps/usbguard-0.7.2/image//usr/bin'
libtool: warning: './libusbguard.la' has not been installed in '/usr/lib64'
libtool: install: /usr/lib/portage/python3.5/ebuild-helpers/xattr/install -c .libs/usbguard-dbus /var/tmp/portage/sys-apps/usbguard-0.7.2/image//usr/sbin/usbguard-dbus
libtool: warning: './libusbguard.la' has not been installed in '/usr/lib64'
libtool: install: /usr/lib/portage/python3.5/ebuild-helpers/xattr/install -c .libs/usbguard /var/tmp/portage/sys-apps/usbguard-0.7.2/image//usr/bin/usbguard
libtool: warning: './libusbguard.la' has not been installed in '/usr/lib64'
libtool: install: /usr/lib/portage/python3.5/ebuild-helpers/xattr/install -c .libs/usbguard-rule-parser /var/tmp/portage/sys-apps/usbguard-0.7.2/image//usr/bin/usbguard-rule-parser
make[3]: Leaving directory '/var/tmp/portage/sys-apps/usbguard-0.7.2/work/usbguard-0.7.2'
make[2]: Leaving directory '/var/tmp/portage/sys-apps/usbguard-0.7.2/work/usbguard-0.7.2'
make[1]: Leaving directory '/var/tmp/portage/sys-apps/usbguard-0.7.2/work/usbguard-0.7.2'
Traceback (most recent call last):
  File "/usr/lib/portage/python3.5/doins.py", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/portage/python3.5/doins.py", line 602, in main
    os.path.dirname(source)):
  File "/usr/lib/portage/python3.5/doins.py", line 450, in _doins
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/python3.5/doins.py", line 386, in install_file
    return self._ins_runner.run(source, dest_dir)
  File "/usr/lib/portage/python3.5/doins.py", line 195, in run
    sstat = os.stat(source)
FileNotFoundError: [Errno 2] No such file or directory: b'usbguard.service'
 * ERROR: sys-apps/usbguard-0.7.2::das-labor failed (install phase):
 *   doins failed

Looks like a misquoted filename or quote in stead of a / ... and  the target *.service files  get filtered out.

Also the instructions here fail for Gentoo.
https://usbguard.github.io/documentation/compilation

also these fail to work:
https://github.com/USBGuard/usbguard/commit/a309209ff803d4fdbf3e212493bb53664bfa0570

**Comment by noci2012** [comment]
examining the ebuild shows that usbguard.service has not been generated from usbguard.service.in

**Comment by noci2012** [comment]
This also requires a few new files : /etc/init.d/usbguard with the following content:

```#!/sbin/openrc-run
# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

description="usbguard - usb device checker"
pidfile="/var/run/usbguard.pid"
command="usbguard-daemon" 
command_args="-p ${pidfile} -f ${USBGUARD_OPTS} -c ${USBGUARD_CONFIG}"
start_stop_daemon_args="--pidfile ${pidfile}"

depend() {
        use dbus logger
        after dbus
}

start_pre() {
        if [ ! -f "${USBGUARD_CONFIG}" ] ; then
                eerror "Please create ${USBGUARD_CONFIG}"
                return 1
        fi
        return 0
}

```

and /etc/conf.d/usbguard
```# select options for usb guard
USBGUARD_OPTS="-s"
# select config file
USBGUARD_CONFIG="/etc/usbguard/usbguard-daemon.conf"
```

the last one might be generated like the systemd.service file (then paths can be generated),
and the .ebuild needs to install these if -systemd is given.  Either from the source (needs usbguard update as well) or from a files directory here.

What is preferred?

**Comment by zaolin** [comment]
source based if possible.

**Comment by noci2012** [comment]
* Digest verification failed:
 * /var/lib/layman/das-labor/sys-apps/usbguard/usbguard-0.7.2.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 2308
 * Expected: 2307
 * Digest verification failed:
 * /var/lib/layman/das-labor/sys-apps/usbguard/usbguard-9999.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 2308
 * Expected: 2307
 * Digest verification failed:
 * /var/lib/layman/das-labor/sys-apps/usbguard/usbguard-0.7.0.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 2308
 * Expected: 2307
 * Digest verification failed:
 * /var/lib/layman/das-labor/sys-apps/usbguard/usbguard-0.6.2.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 2308
 * Expected: 2307

What do you mean with "source based if possible"?
